// Generated by CoffeeScript 1.6.3
define(['router'], function(Router) {
  var app;
  return app = {
    initialize: function() {
      var router;
      router = new Router();
      return Backbone.history.start();
    }
  };
});
