// Generated by CoffeeScript 1.6.3
require.config({
  baseUrl: 'js/libs',
  paths: {
    templates: '../../templates',
    views: '../views',
    router: '../router',
    app: '../app'
  },
  shim: {
    'bootstrap': ['jquery'],
    'backbone': ['underscore', 'jquery'],
    'app': ['backbone', 'bootstrap']
  }
});

require(['app'], function(app) {
  return app.initialize();
});
