// Generated by CoffeeScript 1.8.0
require.config({
  baseUrl: 'js/libs',
  paths: {
    templates: '../../templates',
    views: '../views',
    router: '../router',
    app: '../app',
    vender: '../vendor',
    gPlaces: 'http://maps.googleapis.com/maps/api/js?libraries=places'
  },
  shim: {
    'backbone': ['underscore', 'jquery'],
    'app': ['backbone']
  }
});

require(['app'], function(app) {
  return app.initialize();
});
