// Generated by CoffeeScript 1.8.0
define([], function() {
  var Router;
  return Router = Backbone.Router.extend({
    currentView: null,
    routes: {
      '': 'index',
      'result': 'result'
    },
    change: function(view) {
      var thiz;
      if (this.currentView != null) {
        this.currentView.undelegateEvents();
      }
      thiz = this;
      return require([view], function(View) {
        var next;
        next = new View();
        thiz.currentView = next;
        return thiz.currentView.render();
      });
    },
    index: function() {
      return this.change('views/index');
    },
    result: function() {
      return this.change('views/result');
    }
  });
});
