// Generated by CoffeeScript 1.7.1
define([], function() {
  var Router;
  return Router = Backbone.Router.extend({
    currentView: null,
    routes: {
      '': 'index',
      'result/:id': 'result'
    },
    change: function(view, options) {
      var thiz;
      if (this.currentView != null) {
        this.currentView.undelegateEvents();
      }
      thiz = this;
      return require([view], function(View) {
        var next;
        next = new View(options);
        thiz.currentView = next;
        return thiz.currentView.render();
      });
    },
    index: function() {
      return this.change('views/index');
    },
    result: function(id) {
      var data;
      data = JSON.parse(localStorage.getItem(id));
      return this.change('views/result', {
        data: data
      });
    }
  });
});
