// Generated by CoffeeScript 1.8.0
define(['jquery', 'api', 'utils'], function($, api, utils) {
  var awesomify, ma, mn, mystify, prepare, test;
  mn = {
    distance: {
      lat: 0.8,
      lng: 1.6
    }
  };
  test = function(data) {
    var entry, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      entry = data[_i];
      _results.push(console.log(entry.address_obj.address_string + ' ' + entry.latitude + ' ' + entry.longitude));
    }
    return _results;
  };
  prepare = function(stops, attractions) {
    var a, cities, city, end, end_lat, end_lng, id, ids, key, lat, lng, ranks, result, score, start, start_lat, start_lng, _i, _j, _len, _len1, _ref;
    cities = {};
    ranks = [];
    ids = [];
    start = stops.start;
    end = stops.end;
    start_lat = start.lat < end.lat ? start.lat - mn.distance.lat : start.lat + mn.distance.lat;
    start_lng = start.lng < end.lng ? start.lng - mn.distance.lng : start.lng + mn.distance.lng;
    end_lat = end.lat < start.lat ? end.lat - mn.distance.lat : end.lat + mn.distance.lat;
    end_lng = end.lng < start.lng ? end.lng - mn.distance.lng : end.lng + mn.distance.lng;
    for (_i = 0, _len = attractions.length; _i < _len; _i++) {
      a = attractions[_i];
      id = a.location_id;
      if (ids.indexOf(id) >= 0) {
        continue;
      }
      lat = a.latitude;
      lng = a.longitude;
      if (!(start_lat <= lat && lat <= end_lat || start_lat >= lat && lat >= end_lat)) {
        continue;
      }
      if (!(start_lng <= lng && lng <= end_lng || start_lng >= lng && lng >= end_lng)) {
        continue;
      }
      ids.push(id);
      city = a.ancestors[0].name;
      if (cities[city] == null) {
        cities[city] = [];
      }
      score = (a.percent_recommended * 1.0 / 100.0) * a.num_reviews * a.rating;
      a.score = score;
      cities[city].push(a);
      ranks.push(a);
    }
    _ref = utils.keys(cities);
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      key = _ref[_j];
      cities[key].sort(function(a, b) {
        return b.score - a.score;
      });
    }
    ranks.sort(function(a, b) {
      return b.score - a.score;
    });
    result = {
      cities: cities,
      ranks: ranks
    };
    return result;
  };
  awesomify = function(stops, attractions, cb) {
    var data;
    console.log('attractions to deal with');
    data = prepare(stops, attractions);
    console.log(stops);
    console.log(data);
    return cb(null);
  };
  mystify = function(list, days, cb) {
    var attractions, end, key, keys, number, output, start, subcategories, todo, _fn, _i, _len;
    subcategories = 'landmarks';
    console.log('Something to mystify:');
    console.log(list);
    console.log(days);
    output = {};
    keys = utils.keys(list);
    number = keys.length;
    switch (number) {
      case 1:
        return;
      default:
        start = list[keys[0]];
        end = list[keys[1]];
        todo = 4;
        attractions = [];
        api.taIds({
          lat: start.lat,
          lng: start.lng
        }, function(result) {
          api.taLocation(result.city.id, {
            type: 'attractions',
            subcategory: subcategories
          }, function(result) {
            var item, _i, _len, _ref;
            _ref = result.data;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              attractions.push(item);
            }
            todo--;
            if (todo === 0) {
              return awesomify({
                start: start,
                end: end
              }, attractions, cb);
            }
          });
          return api.taLocation(result.country.id, {
            type: 'attractions',
            subcategory: subcategories
          }, function(result) {
            var item, _i, _len, _ref;
            _ref = result.data;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              attractions.push(item);
            }
            todo--;
            if (todo === 0) {
              return awesomify({
                start: start,
                end: end
              }, attractions, cb);
            }
          });
        });
        api.taIds({
          lat: end.lat,
          lng: end.lng
        }, function(result) {
          api.taLocation(result.city.id, {
            type: 'attractions',
            subcategory: subcategories
          }, function(result) {
            var item, _i, _len, _ref;
            _ref = result.data;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              attractions.push(item);
            }
            todo--;
            if (todo === 0) {
              return awesomify({
                start: start,
                end: end
              }, attractions, cb);
            }
          });
          return api.taLocation(result.country.id, {
            type: 'attractions',
            subcategory: subcategories
          }, function(result) {
            var item, _i, _len, _ref;
            _ref = result.data;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              attractions.push(item);
            }
            todo--;
            if (todo === 0) {
              return awesomify({
                start: start,
                end: end
              }, attractions, cb);
            }
          });
        });
    }
    _fn = function(key) {

      /*
      				item = list[key]
      				api.taMap
      					lat: item.lat
      					lng: item.lng
      				, 'attractions', (result) ->
      					console.log result
       */
    };
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      _fn(key);
    }
    return cb(output);
  };
  return ma = {
    attractions: {
      subcategories: {
        'Other': 'other',
        'Nightlife': 'nightlife',
        'Shopping': 'shopping',
        'Bar': 'bars',
        'Club': 'clubs',
        'Food & Drink': 'food_drink',
        'Ranch Farm': 'ranch_farm',
        'Adventure': 'adventure',
        'Gear Rental': 'gear_rentals',
        'Wellness & Spa': 'wellness_spas',
        'Class': 'classes',
        'Sightseeing Tour': 'sightseeing_tours',
        'Performance': 'performances',
        'Sport': 'sports',
        'Outdoor': 'outdoors',
        'Amusement': 'amusement',
        'Landmark': 'landmarks',
        'Zoo & Aquarium': 'zoos_aquariums',
        'Museums': 'museums',
        'Cultural': 'cultural'
      },
      durations: {
        'Other': 5,
        'Nightlife': 4,
        'Shopping': 2,
        'Bar': 3,
        'Club': 3,
        'Food & Drink': 2,
        'Ranch Farm': 2,
        'Adventure': 4,
        'Gear Rental': 3,
        'Wellness & Spa': 3,
        'Class': 2,
        'Sightseeing Tour': 8,
        'Performance': 3,
        'Sport': 3,
        'Outdoor': 4,
        'Amusement': 4,
        'Landmark': 2,
        'Zoo & Aquarium': 3,
        'Museums': 6,
        'Cultural': 4
      },
      times: {
        'Other': 0,
        'Nightlife': 5,
        'Shopping': 3,
        'Bar': 4,
        'Club': 4,
        'Food & Drink': 4,
        'Ranch Farm': 2,
        'Adventure': 2,
        'Gear Rental': 2,
        'Wellness & Spa': 3,
        'Class': 2,
        'Sightseeing Tour': 1,
        'Performance': 5,
        'Sport': 5,
        'Outdoor': 2,
        'Amusement': 4,
        'Landmark': 2,
        'Zoo & Aquarium': 4,
        'Museums': 2,
        'Cultural': 2
      }
    },
    search: function(input, cb) {
      var city, inserted, list, _i, _len, _ref;
      list = {};
      inserted = [];
      _ref = input.cities;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        city = _ref[_i];
        if (inserted.indexOf(city) >= 0) {
          continue;
        }
        inserted.push(city);
        list[city] = {
          address: city
        };
      }
      return api.geoCode(list, function(result) {
        return mystify(result, input.days, function(result) {
          return cb(result);
        });
      });
    },
    mock: function() {
      var fake;
      fake = [
        {
          day: 1,
          city: {
            name: 'London',
            address: 'London, United Kingdom',
            photo: 'http://i.telegraph.co.uk/multimedia/archive/02423/london_2423609b.jpg'
          },
          attractions: [
            {
              name: 'London Eye',
              duration: 2,
              address: 'Riverside Bldg, County Hall Westminster Bridge Rd London SE1 7PB, United Kingdom',
              photo: 'http://cdn.londonandpartners.com/asset/20adda9d08e8480c6dbbfcf30fbcabdb.jpg'
            }, {
              name: 'The National Gallery',
              duration: 8,
              address: 'Trafalgar Square London WC2N 5DN United Kingdom',
              photo: 'http://ichef.bbci.co.uk/arts/yourpaintings/images/collections/main/NG_collection_image_1.jpg'
            }
          ]
        }
      ];
      return fake;
    }
  };
});
