// Generated by CoffeeScript 1.7.1
define(['jquery', 'api', 'utils'], function($, api, utils) {
  var ma, mystify;
  mystify = function(list, days, cb) {
    var end, key, keys, number, output, start, _fn, _i, _len;
    console.log('Something to mystify:');
    console.log(list);
    console.log(days);
    output = {};
    keys = utils.keys(list);
    number = keys.length;
    switch (number) {
      case 1:
        return;
      default:
        start = list[keys[0]];
        end = list[keys[1]];
        api.taMapBox({
          lat: start.lat,
          lng: start.lng
        }, {
          lat: end.lat,
          lng: end.lng
        }, {
          type: 'attractions'
        }, function(result) {
          return console.log(result);
        });
    }
    _fn = function(key) {

      /*
      				item = list[key]
      				api.taMap
      					lat: item.lat
      					lng: item.lng
      				, 'attractions', (result) ->
      					console.log result
       */
    };
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      _fn(key);
    }
    return cb(output);
  };
  return ma = {
    attractions: {
      subcategories: {
        'Other': 'other',
        'Nightlife': 'nightlife',
        'Shopping': 'shopping',
        'Bar': 'bars',
        'Club': 'clubs',
        'Food & Drink': 'food_drink',
        'Ranch Farm': 'ranch_farm',
        'Adventure': 'adventure',
        'Gear Rental': 'gear_rentals',
        'Wellness & Spa': 'wellness_spas',
        'Class': 'classes',
        'Sightseeing Tour': 'sightseeing_tours',
        'Performance': 'performances',
        'Sport': 'sports',
        'Outdoor': 'outdoors',
        'Amusement': 'amusement',
        'Landmark': 'landmarks',
        'Zoo & Aquarium': 'zoos_aquariums',
        'Museums': 'museums',
        'Cultural': 'cultural'
      }
    },
    search: function(input, cb) {
      var city, inserted, list, _i, _len, _ref;
      list = {};
      inserted = [];
      _ref = input.cities;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        city = _ref[_i];
        if (inserted.indexOf(city) >= 0) {
          continue;
        }
        inserted.push(city);
        list[city] = {
          address: city
        };
      }
      return api.geoCode(list, function(result) {
        return mystify(result, input.days, function(result) {
          return cb(result);
        });
      });
    },
    mock: function() {
      var fake;
      fake = [
        {
          day: 1,
          city: {
            name: 'London',
            address: 'London, United Kingdom',
            photo: 'http://i.telegraph.co.uk/multimedia/archive/02423/london_2423609b.jpg'
          },
          attractions: [
            {
              name: 'London Eye',
              duration: 2,
              address: 'Riverside Bldg, County Hall Westminster Bridge Rd London SE1 7PB, United Kingdom',
              photo: 'http://cdn.londonandpartners.com/asset/20adda9d08e8480c6dbbfcf30fbcabdb.jpg'
            }, {
              name: 'The National Gallery',
              duration: 8,
              address: 'Trafalgar Square London WC2N 5DN United Kingdom',
              photo: 'http://ichef.bbci.co.uk/arts/yourpaintings/images/collections/main/NG_collection_image_1.jpg'
            }
          ]
        }
      ];
      return fake;
    }
  };
});
