// Generated by CoffeeScript 1.7.1
define(['jquery', 'ma', 'vv', 'text!templates/index.html'], function($, ma, vv, template) {
  var IndexView;
  return IndexView = Backbone.View.extend({
    el: $('body'),
    events: {
      'click .btn-search': 'search'
    },
    render: function() {
      this.test();
      this.$el.html(_.template(template)({}));
      return vv.work();
    },
    search: function() {}
  });
});
