// Generated by CoffeeScript 1.6.3
var folder, http, server;

http = require('http');

server = require('node-static');

folder = new server.Server('./');

http.createServer(function(req, res) {
  return req.addListener('end', function() {
    return folder.serve(req, res);
  }).resume();
}).listen(3000);
